"""Regenerates nip01-vectors.json (F-032) with an implementation independent of the C# code under test:
NIP-01 id = sha256 of json.dumps([0,pubkey,created_at,kind,tags,content], separators=(",",":"), ensure_ascii=False),
sig = bitcoin/bips BIP-340 reference implementation (bip340_reference.py, next to this file) with a fixed aux per event
(so the C# signature must match exactly).
Run from the repo root: python tests/TakEngine.Transport.Tests/Vectors/make_nip01_vectors.py"""
import hashlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from bip340_reference import pubkey_gen, schnorr_sign, schnorr_verify  # noqa: E402

sk = hashlib.sha256(b"tak-p2p nip01 vector key").digest()
pk = pubkey_gen(sk).hex()
recipient = pubkey_gen(hashlib.sha256(b"tak-p2p nip01 vector recipient").digest()).hex()
cases = [
    ("plain", 1, [["t", "tak"]], "hello"),
    ("json-specials", 1, [["t", "tak"]], "a1>+ <b2 & \"q\" \\ / end"),
    ("newline-cr-tab", 1, [["t", "tak"]], "line1\nline2\r\n\tend"),
    ("backspace-formfeed", 1, [["t", "tak"]], "ctl \b \f end"),
    ("u0001-u001f", 1, [["t", "tak"]], "ctl \u0001 \u001f end"),
    ("del", 1, [["t", "tak"]], "del \u007f end"),
    ("emoji-surrogate-pair", 1, [["t", "tak"]], "emoji \U0001F984\U0001F355"),
    ("u2028-u2029", 1, [["t", "tak"]], "sep " + chr(0x2028) + " " + chr(0x2029) + " end"),
    ("non-ascii-tag", 1, [["t", "tak", "é表"]], "unicode é表"),
    ("empty-content", 1, [["t", "tak"]], ""),
    ("empty-tags", 1, [], "no tags"),
    ("kind-3825-envelope", 3825, [["p", recipient], ["g", "0b7e3d4c-1f2a-4b5c-8d9e-0f1a2b3c4d5e"]],
     "AgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABee0G5VSK0/9YypIObAtDKfYEAjD35uVkHyB0F4DwrcNaCXlCWZKaArsGrY6M9wnuTMxWfp1RTN9Xga8no+kF5Vsb"),
]
out = {
    "_source": "Generated by make_nip01_vectors.py (Python json + hashlib for the NIP-01 id, bitcoin/bips bip340_reference.py for the signature).",
    "secret_key": sk.hex(),
    "pubkey": pk,
    "events": [],
}
for i, (name, kind, tags, content) in enumerate(cases):
    created_at = 1700000000 + i
    serialized = json.dumps([0, pk, created_at, kind, tags, content], separators=(",", ":"), ensure_ascii=False)
    event_id = hashlib.sha256(serialized.encode("utf-8")).digest()
    aux = hashlib.sha256(("aux-%d" % i).encode()).digest()
    sig = schnorr_sign(event_id, sk, aux)
    assert schnorr_verify(event_id, bytes.fromhex(pk), sig)
    out["events"].append({
        "name": name, "created_at": created_at, "kind": kind, "tags": tags, "content": content,
        "serialized": serialized, "aux": aux.hex(), "id": event_id.hex(), "sig": sig.hex(),
    })
with open(os.path.join(HERE, "nip01-vectors.json"), "w", encoding="ascii", newline="\n") as f:
    f.write(json.dumps(out, indent=2, ensure_ascii=True) + "\n")
print("wrote nip01-vectors.json with %d events" % len(cases))
